### ISSUE TITLE
Changes for DAP draft-02

### ISSUE THREAD

**Issue by divergentdave** [divergentdave/draft-dcook-ppm-dap-interop-test-design#7]
- [x] Update document reference. (#13)
- [x] Change /internal/test/collect_start to permit fixed size batches. This will require some additional communication with the leader, as the protocol does not yet provide a way to determine batch identifiers. (#13)
- [x] Add report count to /internal/test/collect_poll response. (#9)
- [ ] DAP-Auth-Token is no longer mandatory, so the corresponding parameters could be optional, only provided in some test cases.
- [x] Rename "nonceTime" attribute. (aae1bbd)
- [x] Rename minBatchDuration to timePrecision. (#11)
- [x] Rename maxBatchLifetime to maxBatchQueryCount. (7f3942fc21fd6603b9488538d2fece950a23ad9d)
- [x] Update 'Implementation Status' section. (#24)

**Comment by divergentdave** [comment]
I think it may make sense to leave the authentication token parameters as-is for now. Draft 02 only has performance requirements, and suggests OAuth 2 and mTLS as possible approaches. This document would benefit from waiting and seeing what client authentication methods are commonly used by implementations, and then updating based on that.
